### ISSUE TITLE
Django 5 Tests - Community Effort 

### ISSUE THREAD

**Issue by app-generator** [app-generator/rocket-django#30]
To be updated.

**Comment by Alphagest** [comment]
For context, I removed all references to specific versions in the requirements.txt file.
work with latest django (5) and all latests modules.
python3.12.
I also used pipenv to create and activate the virtual environment

the list of problems during installation:


1- **Commande :** `python manage.py makemigrations`
👎**Error :**
```
core\settings.py", line 16, in <module>
       from distutils.util import strtobool
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        ModuleNotFoundError: No module named 'distutils'
```

👍**solution:** `use django-environ instead of dotenv `


2- : **Commande :** `python manage.py makemigrations`
👎 **Error :** 
```
\apps\api\urls.py:8: SyntaxWarning: invalid escape sequence '\d'
  re_path("sales/((?P<pk>\d+)/)?", csrf_exempt(SalesView.as_view())),
```

👍 **Sollution :** `re_path(r"sales/((?P<pk>\d+)/)?", csrf_exempt(SalesView.as_view())),`


3-: **Commande :** `Navigate to users/user-list`
👎 **Error :** 
```
UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'django.contrib.auth.models.User'> QuerySet.
  paginator = Paginator(user_list, 5)
```

👍 **Sollution :add ** `.order_by('username')` to users/views.py ligne 100


💯 with these modifications, everything seems to work correctly

**Comment by app-generator** [comment]
Ty @Alphagest 

All the above is noted.

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
